spring:
  application:
    name: OtmbItApp
zmq:
  channel:
    url: tcp://127.0.0.1:55555
    topic: point
    pubUrl: tcp://*:55556
    pubTopic: control
logging:
  level:
    org.otmb: debug
    org.springframework.integration: debug
